services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379/0
    depends_on:
     - redis
  redis:
    image: redis:8.10.1

  